### ISSUE TITLE
Search series by IMDB ID.

### ISSUE THREAD

**Issue by Freddy12** [sagcan/java-thetvdb#1]
Hi,

in the thetvdb API there is an option to search series by IMDB ID: https://api.thetvdb.com/swagger#!/Search/get_search_series

Would it be possible to add this option in the library?

**Comment by sagcan** [comment]
Hi, sorry for the delayed response but I didn't get any notification whatsoever and stumbled across this by coincidence. Anyways implementing that feature would be very easy in fact (take a look at the `getSeries(int seriesId)` function as well as the `PATH_SEARCH` string). So if you really need that feature why don't you try to implement it and perhaps create a pull request :)?
